{ pkgs, mkLib }:
let
  inherit (pkgs) lib;

  mk = config: mkLib pkgs { inherit config; };

  defaultLib = mk { };
  disabledLib = mk {
    cargo-crap.enable = false;
  };
  noConfigLib = mk {
    cargo-crap.config.enable = false;
  };
  preCommitLib = mk {
    cargo-crap.pre-commit.enable = true;
    cargo-crap.pre-commit.args = [
      "--workspace"
      "--threshold"
      "123"
      "--fail-above"
    ];
  };

  assertMsg = lib.assertMsg;
in
assert assertMsg defaultLib.config.cargo-crap.enable "cargo-crap is enabled by default";
assert assertMsg (
  !defaultLib.config.cargo-crap.pre-commit.enable
) "cargo-crap pre-commit is opt-in";
assert assertMsg (builtins.hasAttr ".cargo-crap.toml" defaultLib.config.rootDir)
  ".cargo-crap.toml is generated by default";
assert assertMsg (builtins.hasAttr "cargo-crap" defaultLib.config.just.rules)
  "just crap recipe is generated by default";
assert assertMsg
  (builtins.elem defaultLib.config.cargo-crap.package defaultLib.config.env.shellPackages)
  "cargo-crap package is included in dev shells";
assert assertMsg (
  !(builtins.hasAttr "cargo_crap" defaultLib.config.git.pre-commit.hooks)
) "cargo-crap pre-commit hook is not generated by default";
assert assertMsg (
  !(builtins.hasAttr ".cargo-crap.toml" disabledLib.config.rootDir)
) "top-level disable removes generated .cargo-crap.toml";
assert assertMsg (
  !(builtins.hasAttr "cargo-crap" disabledLib.config.just.rules)
) "top-level disable removes just recipe";
assert assertMsg (
  !(builtins.elem disabledLib.config.cargo-crap.package disabledLib.config.env.shellPackages)
) "top-level disable removes shell package";
assert assertMsg (
  !(builtins.hasAttr "cargo_crap" disabledLib.config.git.pre-commit.hooks)
) "top-level disable removes pre-commit hook";
assert assertMsg (
  !(builtins.hasAttr ".cargo-crap.toml" noConfigLib.config.rootDir)
) "config disable removes only generated .cargo-crap.toml";
assert assertMsg (builtins.hasAttr "cargo-crap" noConfigLib.config.just.rules)
  "config disable keeps just recipe";
assert assertMsg
  (builtins.elem noConfigLib.config.cargo-crap.package noConfigLib.config.env.shellPackages)
  "config disable keeps shell package";
assert assertMsg (builtins.hasAttr "cargo_crap" preCommitLib.config.git.pre-commit.hooks)
  "pre-commit enable generates hook";
assert assertMsg
  (lib.hasInfix "flakebox-in-each-cargo-workspace cargo-crap" preCommitLib.config.git.pre-commit.hooks.cargo_crap)
  "pre-commit hook invokes cargo-crap directly";
assert assertMsg
  (lib.hasInfix "--threshold 123" preCommitLib.config.git.pre-commit.hooks.cargo_crap)
  "pre-commit args are rendered into hook";

pkgs.runCommand "cargo-crap-module-tests" { } "touch $out"
