{
  pkgs,
  flakeboxLib,
  mkLib,
}:

let
  timer = pkgs.callPackage ../lib/pkgs/git-hook-check-timer.nix { };

  mkHookFixture =
    hooks:
    (mkLib pkgs {
      config.git = {
        pre-commit = {
          trailing_newline = false;
          trailing_whitespace = false;
          hooks = pkgs.lib.mkForce hooks;
        };
        commit-msg.enable = false;
        commit-template.enable = false;
      };
    }).root;

  timedHooks = mkHookFixture {
    "a-slow" = ''
      printf 'a-slow\n' >> "$FLAKEBOX_TEST_LOG"
      touch "$FLAKEBOX_TEST_LOG.a-ready"
      while [ ! -e "$FLAKEBOX_TEST_LOG.c-ready" ]; do sleep 0.01; done
      printf 'slow stdout\n'
      printf 'slow stderr without newline' >&2
      sleep 2
    '';
    "b-fast" = ''
      printf 'b-fast\n' >> "$FLAKEBOX_TEST_LOG"
      printf 'fast stdout without newline'
      printf 'fast stderr without newline' >&2
    '';
    "c-slow" = ''
      printf 'c-slow\n' >> "$FLAKEBOX_TEST_LOG"
      touch "$FLAKEBOX_TEST_LOG.c-ready"
      while [ ! -e "$FLAKEBOX_TEST_LOG.a-ready" ]; do sleep 0.01; done
      sleep 2
    '';
  };

  queueHooks = mkHookFixture {
    "a-blocker" = ''
      sleep 1.2
    '';
    "b-fast-after-queue" = ''
      true
    '';
  };

  stashHooks = mkHookFixture {
    stash-probe = ''
      grep -qx staged tracked.txt
    '';
  };

  stashFailureHooks = mkHookFixture {
    stash-failure = ''
      grep -qx staged tracked.txt
      return 42
    '';
  };

  jjHooks = mkHookFixture {
    jj-probe = ''
      grep -qx unstaged unstaged.txt
    '';
  };

  interruptHooks = mkHookFixture {
    interrupt = ''
      printf ready > "$FLAKEBOX_INTERRUPT_READY"
      while true; do :; done
    '';
  };

  failureHooks = mkHookFixture {
    fail-one = ''
      printf 'fail-one\n' >> "$FLAKEBOX_TEST_LOG"
      return 1
    '';
    fail-42 = ''
      printf 'fail-42\n' >> "$FLAKEBOX_TEST_LOG"
      return 42
    '';
    success = ''
      printf 'success\n' >> "$FLAKEBOX_TEST_LOG"
    '';
  };

  emptyHooks = mkHookFixture { };
in
assert pkgs.lib.elem timer flakeboxLib.config.env.shellPackages;
pkgs.runCommand "git-hooks-tests"
  {
    nativeBuildInputs = [
      pkgs.bash
      pkgs.coreutils
      pkgs.git
      pkgs.gnugrep
      pkgs.gnused
      pkgs.parallel
      timer
    ]
    ++ pkgs.lib.optionals pkgs.stdenv.isLinux [ pkgs.util-linux ];
  }
  ''
    set -euo pipefail

    pre_commit="${flakeboxLib.root}/misc/git-hooks/pre-commit"
    first_line="$(head -n 1 "$pre_commit")"
    if [ "$first_line" != "#!/usr/bin/env bash" ]; then
      echo "pre-commit shebang must be on line 1, got: $first_line" >&2
      exit 1
    fi

    second_line="$(sed -n '2p' "$pre_commit")"
    third_line="$(sed -n '3p' "$pre_commit")"
    if [ "$second_line" != "#" ] || [ "$third_line" != "# NOTE: THIS FILE IS AUTO-GENERATED BY FLAKEBOX" ]; then
      echo "pre-commit generated banner must immediately follow the shebang" >&2
      exit 1
    fi

    bash -n "$pre_commit"
    ! grep -q check_nothing "$pre_commit"
    grep -q '^  flakebox-git-hook-check-timer "\$1"$' "$pre_commit"
    ! grep -q '/nix/store/.*flakebox-git-hook-check-timer' "$pre_commit"
    ! grep -q 'Skipping semgrep check' "$pre_commit"

    commit_msg="${flakeboxLib.root}/misc/git-hooks/commit-msg"
    first_line="$(head -n 1 "$commit_msg")"
    if [ "$first_line" != "#!/usr/bin/env bash" ]; then
      echo "commit-msg shebang must be on line 1, got: $first_line" >&2
      exit 1
    fi
    bash -n "$commit_msg"

    # The timer preserves success, failures, errexit, signals, and byte-exact
    # ordinary output when no warning is emitted.
    function check_output() {
      printf 'stdout line\nstdout-without-newline'
      printf 'stderr line\nstderr-without-newline' >&2
    }
    function check_one() {
      return 1
    }
    function check_42() {
      return 42
    }
    function check_125() {
      return 125
    }
    function check_errexit() {
      set -e
      false
      printf should-not-run
    }
    export -f check_output check_one check_42 check_125 check_errexit

    flakebox-git-hook-check-timer check_output > timer.stdout 2> timer.stderr
    printf 'stdout line\nstdout-without-newline' > expected-timer.stdout
    printf 'stderr line\nstderr-without-newline' > expected-timer.stderr
    cmp expected-timer.stdout timer.stdout
    cmp expected-timer.stderr timer.stderr

    function check_slow_output() {
      printf slow-stderr-without-newline >&2
      sleep 1.2
    }
    export -f check_slow_output
    flakebox-git-hook-check-timer check_slow_output 2> slow-timer.stderr
    sed -E 's/took [0-9]+\.[0-9]{3}s/took DURATION/' \
      slow-timer.stderr > normalized-slow-timer.stderr
    printf 'slow-stderr-without-newline\nflakebox: warning: check_slow_output took DURATION (>1s)\n' \
      > expected-slow-timer.stderr
    cmp expected-slow-timer.stderr normalized-slow-timer.stderr

    set +e
    flakebox-git-hook-check-timer check_one
    one_status=$?
    flakebox-git-hook-check-timer check_42
    status_42=$?
    flakebox-git-hook-check-timer check_125
    status_125=$?
    flakebox-git-hook-check-timer check_errexit > errexit.stdout
    errexit_status=$?
    set -e
    [ "$one_status" -eq 1 ]
    [ "$status_42" -eq 42 ]
    [ "$status_125" -eq 125 ]
    [ "$errexit_status" -eq 1 ]
    [ ! -s errexit.stdout ]

    set +e
    flakebox-git-hook-check-timer 2> timer-error.stderr
    timer_error_status=$?
    set -e
    [ "$timer_error_status" -eq 125 ]
    grep -qx 'flakebox: error: git-hook check timer: missing check name' timer-error.stderr

    function check_signal() {
      trap 'printf forwarded > "$FLAKEBOX_SIGNAL_LOG"; exit 0' TERM
      printf '%s\n' "$BASHPID" > "$FLAKEBOX_SIGNAL_READY"
      while true; do :; done
    }
    export -f check_signal
    export FLAKEBOX_SIGNAL_LOG="$PWD/signal.log"
    export FLAKEBOX_SIGNAL_READY="$PWD/signal.ready"
    flakebox-git-hook-check-timer check_signal &
    timer_pid=$!
    for attempt in $(seq 1 100); do
      [ -e "$FLAKEBOX_SIGNAL_READY" ] && break
      sleep 0.01
    done
    [ -e "$FLAKEBOX_SIGNAL_READY" ]
    kill -TERM "$timer_pid"
    set +e
    wait "$timer_pid"
    signal_status=$?
    set -e
    [ "$signal_status" -eq 143 ]
    [ "$(cat "$FLAKEBOX_SIGNAL_LOG")" = forwarded ]

    # Every configured hook still runs concurrently. Slow warnings are exact,
    # complete records even after unterminated check stderr.
    mkdir timed-repo
    cd timed-repo
    git init -q
    touch tracked
    git add tracked
    export FLAKEBOX_TEST_LOG="$PWD/hooks.log"
    NO_STASH=1 bash ${timedHooks}/misc/git-hooks/pre-commit \
      > hook.stdout 2> hook.stderr

    printf 'a-slow\nb-fast\nc-slow\n' | sort > expected-hooks
    sort hooks.log > actual-hooks
    cmp expected-hooks actual-hooks
    [ "$(grep -c '^flakebox: warning: check_.* took [0-9]*\.[0-9]\{3\}s (>1s)$' hook.stderr)" -eq 2 ]
    [ "$(grep -c '^flakebox: warning: check_a_slow took ' hook.stderr)" -eq 1 ]
    [ "$(grep -c '^flakebox: warning: check_c_slow took ' hook.stderr)" -eq 1 ]
    ! grep -q 'warning: check_b_fast took' hook.stderr
    grep -q 'slow stderr without newline' hook.stderr
    grep -q 'fast stderr without newline' hook.stderr
    grep -q 'slow stdout' hook.stdout
    grep -q 'fast stdout without newline' hook.stdout

    # GNU Parallel's aggregate status and complete coverage are unchanged when
    # checks return distinct non-zero statuses.
    export FLAKEBOX_TEST_LOG="$PWD/failures.log"
    set +e
    NO_STASH=1 bash ${failureHooks}/misc/git-hooks/pre-commit \
      > failures.stdout 2> failures.stderr
    failure_status=$?
    set -e
    [ "$failure_status" -eq 2 ]
    printf 'fail-42\nfail-one\nsuccess\n' | sort > expected-failures
    sort failures.log > actual-failures
    cmp expected-failures actual-failures

    # A -j1 runner proves time spent queued is not charged to a fast check.
    mkdir fake-bin
    cat > fake-bin/parallel <<'EOF'
    #!${pkgs.bash}/bin/bash
    exec ${pkgs.parallel}/bin/parallel -j1 "$@"
    EOF
    chmod +x fake-bin/parallel
    export PATH="$PWD/fake-bin:$PATH"
    NO_STASH=1 bash ${queueHooks}/misc/git-hooks/pre-commit \
      > queue.stdout 2> queue.stderr
    [ "$(grep -c '^flakebox: warning:' queue.stderr)" -eq 1 ]
    grep -q '^flakebox: warning: check_a_blocker took ' queue.stderr
    ! grep -q 'warning: check_b_fast_after_queue took' queue.stderr
    cd ..

    # Private patch restoration exposes indexed content to checks and restores
    # tracked worktree changes afterwards without touching the user stash.
    mkdir stash-repo
    cd stash-repo
    git init -q
    git config user.email flakebox@example.invalid
    git config user.name Flakebox
    printf 'base\n' > tracked.txt
    printf 'base\n' > unstaged.txt
    git add tracked.txt unstaged.txt
    git commit -qm base

    # An older user stash must remain untouched by the hook's private patch.
    printf 'older stash\n' > unstaged.txt
    git stash push -q -m older
    older_stash="$(git rev-parse refs/stash)"

    printf 'staged\n' > tracked.txt
    git add tracked.txt
    printf 'unstaged\n' > unstaged.txt
    bash ${stashHooks}/misc/git-hooks/pre-commit \
      > stash.stdout 2> stash.stderr
    [ "$(cat tracked.txt)" = staged ]
    [ "$(cat unstaged.txt)" = unstaged ]
    [ "$(git rev-parse refs/stash)" = "$older_stash" ]
    [ -z "$(git for-each-ref --format='%(refname)' refs/flakebox/pre-commit/)" ]
    [ ! -s stash.stderr ]

    set +e
    bash ${stashFailureHooks}/misc/git-hooks/pre-commit \
      > stash-failure.stdout 2> stash-failure.stderr
    stash_failure_status=$?
    set -e
    [ "$stash_failure_status" -eq 1 ]
    [ "$(cat tracked.txt)" = staged ]
    [ "$(cat unstaged.txt)" = unstaged ]
    [ "$(git rev-parse refs/stash)" = "$older_stash" ]
    [ -z "$(git for-each-ref --format='%(refname)' refs/flakebox/pre-commit/)" ]
    [ ! -s stash-failure.stderr ]

    ${pkgs.lib.optionalString pkgs.stdenv.isLinux ''
      # Interrupting the whole generated-hook process group terminates workers
      # and still runs the top-level worktree patch restoration trap.
      export FLAKEBOX_INTERRUPT_READY="$PWD/interrupt.ready"
      setsid bash ${interruptHooks}/misc/git-hooks/pre-commit \
        > interrupt.stdout 2> interrupt.stderr &
      interrupt_pid=$!
      for attempt in $(seq 1 100); do
        [ -e "$FLAKEBOX_INTERRUPT_READY" ] && break
        sleep 0.01
      done
      [ -e "$FLAKEBOX_INTERRUPT_READY" ]
      kill -TERM -- "-$interrupt_pid"
      set +e
      wait "$interrupt_pid"
      interrupt_status=$?
      set -e
      [ "$interrupt_status" -eq 143 ]
      [ "$(cat tracked.txt)" = staged ]
      [ "$(cat unstaged.txt)" = unstaged ]
      [ "$(git rev-parse refs/stash)" = "$older_stash" ]
      [ -z "$(git for-each-ref --format='%(refname)' refs/flakebox/pre-commit/)" ]
      ! grep -q 'could not restore uncommitted changes' interrupt.stderr
      ! kill -0 -- "-$interrupt_pid" 2>/dev/null
    ''}

    # A colocated Jujutsu checkout has no staged/unstaged split. The hook must
    # inspect its current tree without manipulating the Git index or refs.
    mkdir .jj
    NO_STASH= bash ${jjHooks}/misc/git-hooks/pre-commit \
      > jj.stdout 2> jj.stderr
    [ "$(cat unstaged.txt)" = unstaged ]
    [ -z "$(git for-each-ref --format='%(refname)' refs/flakebox/pre-commit/)" ]
    [ ! -s jj.stderr ]
    cd ..

    # A configuration with no hooks remains a valid no-op without a sentinel.
    empty_pre_commit="${emptyHooks}/misc/git-hooks/pre-commit"
    bash -n "$empty_pre_commit"
    ! grep -q 'parallel ' "$empty_pre_commit"
    mkdir empty-repo
    cd empty-repo
    git init -q
    NO_STASH=1 bash "$empty_pre_commit"
    cd ..

    touch "$out"
  ''
