{ pkgs, flakeboxLib }:

pkgs.runCommand "git-hooks-tests" { } ''
  set -euo pipefail

  pre_commit="${flakeboxLib.root}/misc/git-hooks/pre-commit"
  first_line="$(${pkgs.coreutils}/bin/head -n 1 "$pre_commit")"
  if [ "$first_line" != "#!/usr/bin/env bash" ]; then
    echo "pre-commit shebang must be on line 1, got: $first_line" >&2
    exit 1
  fi

  second_line="$(${pkgs.gnused}/bin/sed -n '2p' "$pre_commit")"
  third_line="$(${pkgs.gnused}/bin/sed -n '3p' "$pre_commit")"
  if [ "$second_line" != "#" ] || [ "$third_line" != "# NOTE: THIS FILE IS AUTO-GENERATED BY FLAKEBOX" ]; then
    echo "pre-commit generated banner must immediately follow the shebang" >&2
    exit 1
  fi

  ${pkgs.bash}/bin/bash -n "$pre_commit"

  commit_msg="${flakeboxLib.root}/misc/git-hooks/commit-msg"
  first_line="$(${pkgs.coreutils}/bin/head -n 1 "$commit_msg")"
  if [ "$first_line" != "#!/usr/bin/env bash" ]; then
    echo "commit-msg shebang must be on line 1, got: $first_line" >&2
    exit 1
  fi

  ${pkgs.bash}/bin/bash -n "$commit_msg"

  touch "$out"
''
