{
  pkgs,
  mkLib,
}:
let
  inherit (pkgs) lib;
  inherit (lib) assertMsg;
  timer = pkgs.callPackage ../lib/pkgs/git-hook-check-timer.nix { };
  fakeVale = pkgs.writeShellScriptBin "vale" ''
    printf '%s\0' "$@" >> "$VALE_LOG"
  '';

  defaultLib = mkLib pkgs { };
  disabledLib = mkLib pkgs {
    config.vale.enable = false;
  };
  justDisabledLib = mkLib pkgs {
    config.vale.just.enable = false;
  };
  preCommitDisabledLib = mkLib pkgs {
    config.vale.pre-commit.enable = false;
  };
  configuredLib = mkLib pkgs {
    config = {
      vale = {
        package = fakeVale;
        configFile = ".config/vale/with space.ini";
        pre-commit.args = [
          "--minAlertLevel"
          "warning level"
          "$HOME; do not run"
        ];
      };
      cargo.pre-commit.cargo-lock.enable = false;
      git.pre-commit = {
        trailing_newline = false;
        trailing_whitespace = false;
      };
      ast-grep.enable = false;
      semgrep.enable = false;
      shellcheck.enable = false;
      treefmt.enable = false;
      typos.enable = false;
    };
  };
  invalidConfigFile = builtins.tryEval (
    builtins.deepSeq
      (mkLib pkgs {
        config.vale.configFile = "config\nfile";
      }).config.vale.configFile
      true
  );
  invalidPreCommitArg = builtins.tryEval (
    builtins.deepSeq
      (mkLib pkgs {
        config.vale.pre-commit.args = [ "argument\nvalue" ];
      }).config.vale.pre-commit.args
      true
  );
in
assert assertMsg defaultLib.config.vale.enable "Vale is enabled by default";
assert assertMsg defaultLib.config.vale.just.enable "Vale just recipe is enabled by default";
assert assertMsg defaultLib.config.vale.pre-commit.enable
  "Vale pre-commit hook is enabled by default";
assert assertMsg (builtins.hasAttr "vale" defaultLib.config.just.rules)
  "Vale just recipe is generated by default";
assert assertMsg (builtins.hasAttr "vale" defaultLib.config.git.pre-commit.hooks)
  "Vale pre-commit hook is generated by default";
assert assertMsg (lib.elem pkgs.vale defaultLib.config.env.shellPackages)
  "Vale package is added to development shells";
assert assertMsg (
  !(builtins.hasAttr "vale" disabledLib.config.just.rules)
) "top-level disable removes the Vale just recipe";
assert assertMsg (
  !(builtins.hasAttr "vale" disabledLib.config.git.pre-commit.hooks)
) "top-level disable removes the Vale pre-commit hook";
assert assertMsg (
  !(lib.elem pkgs.vale disabledLib.config.env.shellPackages)
) "top-level disable removes the Vale package";
assert assertMsg (
  !(builtins.hasAttr "vale" justDisabledLib.config.just.rules)
) "just disable removes only the Vale just recipe";
assert assertMsg (builtins.hasAttr "vale" justDisabledLib.config.git.pre-commit.hooks)
  "just disable preserves the Vale pre-commit hook";
assert assertMsg (
  !(builtins.hasAttr "vale" preCommitDisabledLib.config.git.pre-commit.hooks)
) "pre-commit disable removes only the Vale hook";
assert assertMsg (builtins.hasAttr "vale" preCommitDisabledLib.config.just.rules)
  "pre-commit disable preserves the Vale just recipe";
assert assertMsg (lib.elem fakeVale configuredLib.config.env.shellPackages)
  "a custom Vale package replaces the default package";
assert assertMsg (
  !(lib.elem pkgs.vale configuredLib.config.env.shellPackages)
) "a custom Vale package removes the default package";
assert assertMsg
  (lib.hasInfix "--config '.config/vale/with space.ini' \"\$@\" -- \"\${vale_paths[@]}\"" configuredLib.config.just.rules.vale.content)
  "custom config path is rendered into the just recipe";
assert assertMsg
  (lib.hasInfix "--minAlertLevel 'warning level' '$HOME; do not run'" configuredLib.config.git.pre-commit.hooks.vale)
  "pre-commit arguments are shell escaped and rendered into the hook";
assert assertMsg (!invalidConfigFile.success) "config path rejects newlines";
assert assertMsg (!invalidPreCommitArg.success) "pre-commit arguments reject newlines";
pkgs.runCommand "vale-module-tests"
  {
    nativeBuildInputs = [
      fakeVale
      pkgs.bash
      pkgs.coreutils
      pkgs.git
      pkgs.gnugrep
      pkgs.just
      pkgs.parallel
      timer
    ];
  }
  ''
    set -euo pipefail

    mkdir repo
    cd repo
    git init -q
    touch tracked.md
    touch ignored.txt
    touch -- --output=JSON.md
    mkdir .direnv
    touch .direnv/untracked.md
    git add tracked.md ignored.txt -- --output=JSON.md

    export VALE_LOG="$PWD/vale.log"
    pre_commit="${configuredLib.root}/misc/git-hooks/pre-commit"

    NO_STASH=1 bash "$pre_commit"
    [ ! -e "$VALE_LOG" ]

    mkdir -p .config/vale
    touch ".config/vale/with space.ini"
    NO_STASH=1 bash "$pre_commit"
    [ ! -e "$VALE_LOG" ]

    printf '[*]\nBasedOnStyles = Vale\n' > ".config/vale/with space.ini"
    NO_STASH=1 bash "$pre_commit"
    printf '%s\0' \
      "--config" \
      ".config/vale/with space.ini" \
      "--minAlertLevel" \
      "warning level" \
      '$HOME; do not run' \
      "--" \
      "--output=JSON.md" \
      "tracked.md" \
      > expected.log
    cmp expected.log "$VALE_LOG"

    just --working-directory "$PWD" --justfile "${configuredLib.root}/justfile" vale
    printf '%s\0' \
      "--config" \
      ".config/vale/with space.ini" \
      "--" \
      "--output=JSON.md" \
      "tracked.md" \
      >> expected.log
    cmp expected.log "$VALE_LOG"

    just --working-directory "$PWD" --justfile "${configuredLib.root}/justfile" vale \
      "argument with spaces" \
      '$HOME' \
      '; do not run' \
      "a'b"
    printf '%s\0' \
      "--config" \
      ".config/vale/with space.ini" \
      "argument with spaces" \
      '$HOME' \
      '; do not run' \
      "a'b" \
      "--" \
      "--output=JSON.md" \
      "tracked.md" \
      >> expected.log
    cmp expected.log "$VALE_LOG"

    mkdir no-markdown
    cd no-markdown
    git init -q
    mkdir -p .config/vale
    printf '[*]\nBasedOnStyles = Vale\n' > ".config/vale/with space.ini"
    export VALE_LOG="$PWD/vale.log"
    NO_STASH=1 bash "$pre_commit"
    [ ! -e "$VALE_LOG" ]
    just --working-directory "$PWD" --justfile "${configuredLib.root}/justfile" vale
    [ ! -e "$VALE_LOG" ]

    touch "$out"
  ''
